# Sonata Admin Sections Configuration

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#############################################
## Content
#############################################

    # Content / Blog
    admin.blog:
        class: AppBundle\Admin\BlogAdmin
        arguments: [~, AppBundle\Entity\Blog, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.blog }
        public: true

    admin.blog_photo:
        class: AppBundle\Admin\BlogPhotoAdmin
        arguments: [~, AppBundle\Entity\BlogPhoto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        public: true

    # Content / Clients
    admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.clients }
        public: true

    # Content / Crew
    admin.crew:
        class: AppBundle\Admin\CrewAdmin
        arguments: [~, AppBundle\Entity\Crew, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.crew }
        public: true

    # Content / Projects
    admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.projects }
        public: true

    admin.project_photo:
        class: AppBundle\Admin\ProjectPhotoAdmin
        arguments: [~, AppBundle\Entity\ProjectPhoto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        public: true

    admin.project_type:
        class: AppBundle\Admin\ProjectTypeAdmin
        arguments: [~, AppBundle\Entity\ProjectType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.project_types }
        public: true

    # Content / Gallery
    admin.gallery:
        class: AppBundle\Admin\GalleryAdmin
        arguments: [~, AppBundle\Entity\Gallery, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.gallery }
        public: true

#############################################
## Blocks
#############################################

    # Blocks / Index
    admin.page.index:
        class: AppBundle\Admin\PageIndexAdmin
        arguments: [~, AppBundle\Entity\Content, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.page.index }
        public: true

    # Blocks / Contacts
    admin.page.contact:
        class: AppBundle\Admin\PageContactAdmin
        arguments: [~, AppBundle\Entity\Content, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.page.contact }
        public: true

    # Blocks / About
    admin.page.about:
        class: AppBundle\Admin\PageAboutAdmin
        arguments: [~, AppBundle\Entity\Content, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.page.about }
        public: true

#############################################
## Settings
#############################################

    # Settings / Contacts
    admin.contacts:
        class: AppBundle\Admin\ContactsAdmin
        arguments: [~, AppBundle\Entity\Content, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.contacts }
        public: true

    # Settings / SEO
    admin.seo:
        class: AppBundle\Admin\SeoAdmin
        arguments: [~, AppBundle\Entity\Content, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: admin.label.seo }
        public: true