# Sonata Media Configuration

sonata_media:

#############################################
## Storage
#############################################

    db_driver: doctrine_orm
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

#############################################
## Context
#############################################

    default_context: default
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - admin.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    #########################################
    ## Blog
    #########################################

        blog.background:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - admin.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                default: { width: 1920 , quality: 60}
                list: { width: 490, height: 342 , quality: 80}

        blog.photo:
            providers:
                - admin.provider.image
            formats:
                default: { width: 1920 , quality: 60}

        blog.video:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                default: { width: 600 }

    #########################################
    ## Client
    #########################################

        client.logo:
            providers:
                - admin.provider.image
            formats:
                default: { height: 115 , quality: 90}

    #########################################
    ## Crew
    #########################################

        crew.photo:
            providers:
                - admin.provider.image
            formats:
                default: { width: 180, height: 180 , quality: 70}

    #########################################
    ## Gallery
    #########################################

        gallery.photo:
            providers:
                - admin.provider.image
            formats:
                default: { height: 900 , quality: 80}

    #########################################
    ## Projects
    #########################################

        project.photo:
            providers:
                - admin.provider.image
            formats:
                default: { width: 1920 , quality: 60}

        project.logo:
            providers:
                - admin.provider.image
            formats:
                default: { width: 210 , quality: 90}

        project.video:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                default: { width: 600 }

        project.background:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - admin.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                default: { width: 1920 , quality: 60}
                list: { width: 490, height: 342 , quality: 80}

#########################################
## Image Provider with SVG Support
#########################################

services:
    admin.provider.image:
        class: AppBundle\Provider\ImageProvider
        tags:
            - { name: sonata.media.provider }
        arguments:
            - "admin.provider.image"
            - "@sonata.media.filesystem.local"
            - "@sonata.media.cdn.server"
            - "@sonata.media.generator.default"
            - "@sonata.media.thumbnail.format"
            - ['gif', 'svg', 'jpg', 'jpeg', 'png']
            - ['image/svg+xml', 'image/gif', 'image/jpeg', 'image/pjpeg', 'image/png']
            - "@sonata.media.adapter.image.default"
            - "@sonata.media.metadata.proxy"
        calls:
            - [ setTemplates, [{ helper_thumbnail : 'AppBundle:Provider:thumbnail.html.twig', helper_view : 'AppBundle:Provider:view_image.html.twig' }]]