# Sonata Media Configuration

sonata_media:

#############################################
## Storage
#############################################

    db_driver: doctrine_orm
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

#############################################
## Thumbnails settings
#############################################

    default_context: default
    contexts:
        default:
            providers:
                - admin.provider.image
            formats:

                # Blog and Project background
                background:
                    width: 1920
                    height: 1080
                    quality: 50

                # Blog and Project list item
                list:
                    width: 490
                    height: 342
                    quality: 70

                # Gallery, Blog and Project photo
                photo:
                    width: 1280
                    height: 720
                    quality: 80

                # Project logo
                project:
                    width: 210
                    quality: 90

                # Employee photo
                crew:
                    width: 180
                    height: 180
                    quality: 70

        video:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                default:
                    width: 900


#########################################
## Image Provider with SVG Support
#########################################

services:
    admin.provider.image:
        class: AppBundle\Provider\ImageProvider
        tags:
            - { name: sonata.media.provider }
        arguments:
            - "admin.provider.image"
            - "@sonata.media.filesystem.local"
            - "@sonata.media.cdn.server"
            - "@sonata.media.generator.default"
            - "@sonata.media.thumbnail.format"
            - ['gif', 'svg', 'jpg', 'jpeg', 'png']
            - ['image/svg+xml', 'image/gif', 'image/jpeg', 'image/pjpeg', 'image/png']
            - "@sonata.media.adapter.image.default"
            - "@sonata.media.metadata.proxy"
            - "@sonata.media.resizer.simple"
        calls:
            - [ setTemplates, [{ helper_thumbnail : 'AppBundle:Provider:thumbnail.html.twig', helper_view : 'AppBundle:Provider:view_image.html.twig' }]]