# CKEditor Configuration

ivory_ck_editor:
    default_config: default
    configs:
        default:
            # default toolbar plus Format button
            toolbar:
            - [Format, -, Bold, Italic, Underline, -, Cut, Copy, Paste, PasteText, PasteFromWord, -, Undo, Redo, -, NumberedList, BulletedList, -, Outdent, Indent, -, Blockquote, -, Image, Link, Unlink, Table]
            - [Maximize, Source]

            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserBrowseRouteParameters:
                provider: sonata.media.provider.file
                context: default

            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
                context: default

            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRouteParameters:
                provider: admin.provider.image
                context: default

            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: admin.provider.image
                context: default